version: "3"
 
services:
  guacamole:
    image: flcontainers/guacamole:latest
    container_name: guacamole
    restart: unless-stopped
    network_mode: host
    volumes:
      - guac-config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Australia/Sydney"
    # ports removed - not needed with host networking
 
volumes:
  guac-config:
    driver: local